language: android
jdk: openjdk8

android:
  components:
    - build-tools-23.0.1
    - android-23
    - android-18
    - extra
    - sys-img-armeabi-v7a-android-18

install:
   - TERM=dumb

   # Emulator Management: Create, Start and Wait
before_script:
    - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
    - emulator -avd test -engine classic -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
    - ./test_script.sh
    
licences:
    - /android-sdk-license-[0-9a-f]{8}/
cache:
    directories:
    - /home/travis/.gradle/caches/
    - /home/travis/.gradle/wrapper/dists/gradle-2.4-all/
    - /home/travis/.m2/repository/
